target:
	g++ -O3 caffe2txt.cc -o caffe2txt -I/home/zt/caffe/build/src/caffe/proto/ /home/zt/caffe/build/src/caffe/proto/caffe.pb.o -lprotobuf -std=c++11
#-I/home/zt/caffe/build/src/caffe/proto/  We need to be able to find caffe.pb.h 就是定位这个头文件 